version: '3.9'

# Network
networks:
  web_network:
    name: reactwebappts
    driver: bridge

# Services
services:
  # React Web App Service
  reactwebapp:
    container_name: reactwebappts
    image: reactwebappts
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - web_network
